### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Milaan1337** [Milaan1337/cheapsteamaccs#1]
- [x] Min. 20 product
- [x] Normális product képek
- [x] Normális product árak, ne legyen minden leárazva
- [x] site email
- [ ] Product bundlek, osszerako(premium)[optional]
- [x] Product tagek regiok alapjan
- [x] Instagram site setup with followers
- [ ] Instagram site marketing inditasa
- [x] Használati útmutató, mit kap a felhasználó
- [x] ÁSZF
- [x] Garancia 
- [x] Adatkezelesi tajekoztato
- [ ] Review irasa
- [x] Idozitett akcio
- [x] Stu foto kitorlese
- [x] Bundle szovegszin feherre vagy sargara
- [x] Kiadas, profit
- [x] Announce bar edit
- [x] Blog
- [ ] Iphone angol nyelv nem mukodik a fostos currency conversion.
- [x] SEO
- [x] Blog post irasa
